### ISSUE TITLE
some simple enhancement requests

### ISSUE THREAD

**Issue by zehawki** [danielma/unsplash-react#26]
Thank for you this great library and documentation. I some simple enhancement requests:

1. Override the API params - It would be good to expose the Unsplash API search params as props so that the defaults can be overridden. Eg I certainly want to change `per_page` and `content_filter`.
2. No initial default API call - results should show only upon search, not otherwise
2. Show native aspect ratio in search results - I would like to see image native aspect ratio in search results to get a sense of how the image would look when inserted. However I don't see any props to control this. (Or would implementing this totally break your grid display?)

**Comment by danielma** [comment]
Hi @zehawki!

These are things I'd be open to adding to the library. As it is right now, I don't have the bandwidth to implement them, but would happily review PRs and collaborate on discussions about how to implement them

**Comment by zehawki** [comment]
No problem, thanks :-) I've just created my own fresh component. Too many changes are required in this library to meet Unsplash API guidelines for approval.
